function Hd = filter_lpf_Butterworth(Fc, Fs, N)
%FILTER_LPF_BUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 25-Jun-2019 17:15:18

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.

if 1 > nargin
    Fc = 60;  % Cutoff Frequency
end

if 2 > nargin
    Fs = 100000;  % Sampling Frequency
end

if 3 > nargin
    N  = 6;   % Order
end

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
