
% function [Slfp, st] = spec_LFP

x = lfp_st.avg(:,3);
% x = mua_st.avg(:,3);
fs = 500;
win_size_ms = 50;
n_bands = 30;
binwidth = 2;

f_scale = 'lin';
spectrogram_type = 'stft';  
% spectrogram_type = 'multitaper'; 

[Slfp, st] = spec.spectrogram(x, fs, ...
    'n_bands', n_bands,...
    'lowfreq', 1,...
    'highfreq', 250,...
    'overlap_ratio', 0.80,...
    'binwidth', binwidth,...
    'win_size_ms', win_size_ms, ...
    'f_scale', f_scale,...
    'nw', 2,...
    ...'duration_ms', duration_ms,...
    'method', spectrogram_type, ...
    'fignum', 10 ...
 );
